-- MySQL Script generated by MySQL Workbench
-- Thu Oct 12 15:53:47 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd_paiVapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_paiVapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_paiVapp` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `bd_paiVapp` ;

-- -----------------------------------------------------
-- Table `bd_paiVapp`.`t_pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_paiVapp`.`t_pais` ;

CREATE TABLE IF NOT EXISTS `bd_paiVapp`.`t_pais` (
  `idt_pais` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `nacionalidad` VARCHAR(50) NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`idt_pais`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `bd_paiVapp`.`t_departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_paiVapp`.`t_departamento` ;

CREATE TABLE IF NOT EXISTS `bd_paiVapp`.`t_departamento` (
  `idt_departamento` INT NOT NULL AUTO_INCREMENT,
  `idt_pais` INT NOT NULL,
  `cod_departamento` INT NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`idt_departamento`),
  INDEX `fk_t_departamento_t_pais1_idx` (`idt_pais` ASC),
  CONSTRAINT `fk_t_departamento_t_pais1`
    FOREIGN KEY (`idt_pais`)
    REFERENCES `bd_paiVapp`.`t_pais` (`idt_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_paiVapp`.`t_distrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_paiVapp`.`t_distrito` ;

CREATE TABLE IF NOT EXISTS `bd_paiVapp`.`t_distrito` (
  `idt_distrito` INT NOT NULL AUTO_INCREMENT,
  `idt_departamento` INT NOT NULL,
  `cod_distrito` INT NULL,
  `descripcion` VARCHAR(60) NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`idt_distrito`),
  INDEX `fk_t_distrito_t_departamento1_idx` (`idt_departamento` ASC),
  CONSTRAINT `fk_t_distrito_t_departamento1`
    FOREIGN KEY (`idt_departamento`)
    REFERENCES `bd_paiVapp`.`t_departamento` (`idt_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_paiVapp`.`t_edades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_paiVapp`.`t_edades` ;

CREATE TABLE IF NOT EXISTS `bd_paiVapp`.`t_edades` (
  `idt_edades` INT NOT NULL AUTO_INCREMENT,
  `semanas` INT NOT NULL,
  `descripcion` VARCHAR(30) NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`idt_edades`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_paiVapp`.`t_biologicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_paiVapp`.`t_biologicos` ;

CREATE TABLE IF NOT EXISTS `bd_paiVapp`.`t_biologicos` (
  `idt_biologicos` INT NOT NULL AUTO_INCREMENT,
  `nom_biologico` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(80) NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`idt_biologicos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_paiVapp`.`t_dosisB`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_paiVapp`.`t_dosisB` ;

CREATE TABLE IF NOT EXISTS `bd_paiVapp`.`t_dosisB` (
  `idt_dosisB` INT NOT NULL AUTO_INCREMENT,
  `idt_edades` INT NOT NULL,
  `idt_biologicos` INT NOT NULL,
  `dosis` INT NOT NULL,
  `descripcion` VARCHAR(25) NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`idt_dosisB`, `idt_edades`, `idt_biologicos`),
  INDEX `fk_t_dosisB_t_edades1_idx` (`idt_edades` ASC),
  INDEX `fk_t_dosisB_t_biologicos1_idx` (`idt_biologicos` ASC),
  CONSTRAINT `fk_t_dosisB_t_edades1`
    FOREIGN KEY (`idt_edades`)
    REFERENCES `bd_paiVapp`.`t_edades` (`idt_edades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_dosisB_t_biologicos1`
    FOREIGN KEY (`idt_biologicos`)
    REFERENCES `bd_paiVapp`.`t_biologicos` (`idt_biologicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_paiVapp`.`t_tarjeta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_paiVapp`.`t_tarjeta` ;

CREATE TABLE IF NOT EXISTS `bd_paiVapp`.`t_tarjeta` (
  `idt_tarjeta` INT NOT NULL AUTO_INCREMENT,
  `num_ci` INT NULL,
  `ci_cod` VARCHAR(15) NULL,
  `p_nombre` VARCHAR(15) NULL,
  `s_nombre` VARCHAR(15) NULL,
  `t_nombre` VARCHAR(15) NULL,
  `p_apellido` VARCHAR(20) NULL,
  `s_apellido` VARCHAR(20) NULL,
  `fecha_nacimiento` DATE NULL,
  `idt_pais_nac` INT NOT NULL,
  `sexo` CHAR(1) NULL,
  `ci_madre` INT NULL,
  `ci_padre_tutor` INT NULL,
  `t_departamento_idt_departamento` INT NOT NULL,
  `t_distrito_idt_distrito` INT NOT NULL,
  `barrio` VARCHAR(50) NULL,
  `direccion` VARCHAR(100) NULL,
  `localidad` INT NULL,
  `com_indigena` INT NULL,
  `descrip_etnia` VARCHAR(45) NULL,
  `alergia` INT NULL,
  `vacuna_T` INT NULL,
  `vacuna_T_descrip` VARCHAR(50) NULL,
  `medicament_T` INT NULL,
  `medicamento_T_descrip` VARCHAR(50) NULL,
  `otros_T` INT NULL,
  `otros_T_descrip` VARCHAR(50) NULL,
  `estado_nutri` INT NULL,
  `riesgo_nutri` INT NULL,
  `lact_mat` INT NULL,
  `seguro_medico` INT NULL,
  `seguro_tipo` INT NULL,
  `seguro_desc` VARCHAR(45) NULL,
  `fecha_reg` DATE NULL,
  `fecha_ult_visita` DATE NULL,
  PRIMARY KEY (`idt_tarjeta`),
  INDEX `fk_t_tarjeta_t_distrito1_idx` (`t_distrito_idt_distrito` ASC),
  INDEX `fk_t_tarjeta_t_departamento1_idx` (`t_departamento_idt_departamento` ASC),
  INDEX `fk_t_tarjeta_t_pais1_idx` (`idt_pais_nac` ASC),
  CONSTRAINT `fk_t_tarjeta_t_distrito1`
    FOREIGN KEY (`t_distrito_idt_distrito`)
    REFERENCES `bd_paiVapp`.`t_distrito` (`idt_distrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_tarjeta_t_departamento1`
    FOREIGN KEY (`t_departamento_idt_departamento`)
    REFERENCES `bd_paiVapp`.`t_departamento` (`idt_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_tarjeta_t_pais1`
    FOREIGN KEY (`idt_pais_nac`)
    REFERENCES `bd_paiVapp`.`t_pais` (`idt_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_paiVapp`.`t_reg_v`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_paiVapp`.`t_reg_v` ;

CREATE TABLE IF NOT EXISTS `bd_paiVapp`.`t_reg_v` (
  `idt_reg_v` INT NOT NULL AUTO_INCREMENT,
  `t_tarjeta_idt_tarjeta` INT NOT NULL,
  `fecha_vac` DATE NOT NULL,
  `t_dosisB_idt_edades` INT NOT NULL,
  `t_dosisB_idt_biologicos` INT NOT NULL,
  `t_dosisB_idt_dosisB` INT NOT NULL,
  `lote_biolog` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idt_reg_v`, `t_tarjeta_idt_tarjeta`, `t_dosisB_idt_edades`, `t_dosisB_idt_biologicos`, `t_dosisB_idt_dosisB`),
  INDEX `fk_t_reg_v_t_tarjeta1_idx` (`t_tarjeta_idt_tarjeta` ASC),
  INDEX `fk_t_reg_v_t_dosisB1_idx` (`t_dosisB_idt_dosisB` ASC, `t_dosisB_idt_edades` ASC, `t_dosisB_idt_biologicos` ASC),
  CONSTRAINT `fk_t_reg_v_t_tarjeta1`
    FOREIGN KEY (`t_tarjeta_idt_tarjeta`)
    REFERENCES `bd_paiVapp`.`t_tarjeta` (`idt_tarjeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_reg_v_t_dosisB1`
    FOREIGN KEY (`t_dosisB_idt_dosisB` , `t_dosisB_idt_edades` , `t_dosisB_idt_biologicos`)
    REFERENCES `bd_paiVapp`.`t_dosisB` (`idt_dosisB` , `idt_edades` , `idt_biologicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_paiVapp`.`t_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_paiVapp`.`t_rol` ;

CREATE TABLE IF NOT EXISTS `bd_paiVapp`.`t_rol` (
  `idt_rol` INT NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idt_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_paiVapp`.`t_pagina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_paiVapp`.`t_pagina` ;

CREATE TABLE IF NOT EXISTS `bd_paiVapp`.`t_pagina` (
  `idt_pagina` INT NOT NULL AUTO_INCREMENT,
  `pagina` VARCHAR(45) NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`idt_pagina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_paiVapp`.`t_rolXpag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_paiVapp`.`t_rolXpag` ;

CREATE TABLE IF NOT EXISTS `bd_paiVapp`.`t_rolXpag` (
  `idt_rolXpag` INT NOT NULL AUTO_INCREMENT,
  `idt_rol` INT NOT NULL,
  `idt_pagina` INT NOT NULL,
  `permiso` VARCHAR(45) NOT NULL,
  `tipo` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`idt_rolXpag`),
  INDEX `fk_t_rolXpag_t_pagina1_idx` (`idt_pagina` ASC),
  INDEX `fk_t_rolXpag_t_rol1_idx` (`idt_rol` ASC),
  CONSTRAINT `fk_t_rolXpag_t_pagina1`
    FOREIGN KEY (`idt_pagina`)
    REFERENCES `bd_paiVapp`.`t_pagina` (`idt_pagina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_rolXpag_t_rol1`
    FOREIGN KEY (`idt_rol`)
    REFERENCES `bd_paiVapp`.`t_rol` (`idt_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_paiVapp`.`t_reg_sanitaria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_paiVapp`.`t_reg_sanitaria` ;

CREATE TABLE IF NOT EXISTS `bd_paiVapp`.`t_reg_sanitaria` (
  `idt_reg_sanitaria` INT NOT NULL AUTO_INCREMENT,
  `idt_pais` INT NOT NULL,
  `idt_departamento` INT NOT NULL,
  `idt_distrito` INT NOT NULL,
  `cod_reg` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`idt_reg_sanitaria`),
  INDEX `fk_t_reg_sanitaria_t_pais1_idx` (`idt_pais` ASC),
  INDEX `fk_t_reg_sanitaria_t_departamento1_idx` (`idt_departamento` ASC),
  INDEX `fk_t_reg_sanitaria_t_distrito1_idx` (`idt_distrito` ASC),
  CONSTRAINT `fk_t_reg_sanitaria_t_pais1`
    FOREIGN KEY (`idt_pais`)
    REFERENCES `bd_paiVapp`.`t_pais` (`idt_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_reg_sanitaria_t_departamento1`
    FOREIGN KEY (`idt_departamento`)
    REFERENCES `bd_paiVapp`.`t_departamento` (`idt_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_reg_sanitaria_t_distrito1`
    FOREIGN KEY (`idt_distrito`)
    REFERENCES `bd_paiVapp`.`t_distrito` (`idt_distrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_paiVapp`.`t_cat_serv`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_paiVapp`.`t_cat_serv` ;

CREATE TABLE IF NOT EXISTS `bd_paiVapp`.`t_cat_serv` (
  `idt_cat_serv` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`idt_cat_serv`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_paiVapp`.`t_servicio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_paiVapp`.`t_servicio` ;

CREATE TABLE IF NOT EXISTS `bd_paiVapp`.`t_servicio` (
  `idt_servicio` INT NOT NULL AUTO_INCREMENT,
  `idt_reg_sanitaria` INT NOT NULL,
  `cod_servicio` VARCHAR(45) NULL,
  `nombre_serv` VARCHAR(80) NOT NULL,
  `idt_cat_serv` INT NOT NULL,
  `cabecera` INT NOT NULL,
  `tipo_local` INT NOT NULL,
  `idt_departamento` INT NOT NULL,
  `distancia_a_reg_s` INT NULL,
  `poblacion` INT NULL,
  `estado` INT NULL,
  PRIMARY KEY (`idt_servicio`, `idt_reg_sanitaria`),
  INDEX `fk_t_servicio_t_reg_sanitaria1_idx` (`idt_reg_sanitaria` ASC),
  INDEX `fk_t_servicio_t_departamento1_idx` (`idt_departamento` ASC),
  INDEX `fk_t_servicio_t_cat_serv1_idx` (`idt_cat_serv` ASC),
  CONSTRAINT `fk_t_servicio_t_reg_sanitaria1`
    FOREIGN KEY (`idt_reg_sanitaria`)
    REFERENCES `bd_paiVapp`.`t_reg_sanitaria` (`idt_reg_sanitaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_servicio_t_departamento1`
    FOREIGN KEY (`idt_departamento`)
    REFERENCES `bd_paiVapp`.`t_departamento` (`idt_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_servicio_t_cat_serv1`
    FOREIGN KEY (`idt_cat_serv`)
    REFERENCES `bd_paiVapp`.`t_cat_serv` (`idt_cat_serv`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_paiVapp`.`t_personal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_paiVapp`.`t_personal` ;

CREATE TABLE IF NOT EXISTS `bd_paiVapp`.`t_personal` (
  `idt_personal` INT NOT NULL AUTO_INCREMENT,
  `nombre_apellido` VARCHAR(150) NOT NULL,
  `cargo` VARCHAR(50) NOT NULL,
  `idt_servicio` INT NOT NULL,
  `telefono` VARCHAR(15) NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`idt_personal`),
  INDEX `fk_t_personal_t_servicio1_idx` (`idt_servicio` ASC),
  CONSTRAINT `fk_t_personal_t_servicio1`
    FOREIGN KEY (`idt_servicio`)
    REFERENCES `bd_paiVapp`.`t_servicio` (`idt_servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_paiVapp`.`t_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_paiVapp`.`t_usuario` ;

CREATE TABLE IF NOT EXISTS `bd_paiVapp`.`t_usuario` (
  `idt_usuario` INT NOT NULL AUTO_INCREMENT,
  `idt_personal` INT NOT NULL,
  `nick` VARCHAR(10) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `idt_rol` INT NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idt_usuario`, `idt_rol`),
  INDEX `fk_t_usuario_t_rol1_idx` (`idt_rol` ASC),
  INDEX `fk_t_usuario_t_personal1_idx` (`idt_personal` ASC),
  CONSTRAINT `fk_t_usuario_t_rol1`
    FOREIGN KEY (`idt_rol`)
    REFERENCES `bd_paiVapp`.`t_rol` (`idt_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_usuario_t_personal1`
    FOREIGN KEY (`idt_personal`)
    REFERENCES `bd_paiVapp`.`t_personal` (`idt_personal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
